import {
	ajaxDelete,
	ajaxGet,
	ajaxPatch,
	ajaxPost,
	getApiUrl,
} from '@healthvisa/utils';
import {ReferralAPI, Service} from './api';

export interface IReferralCode {
	id: string;
	code: string; // unique, uppercased, auto-generated by the server (immutable)
	referrerName: string;
	isActive: boolean;
	usageCount: number; // read-only in UI
	validFrom?: string;
	validTo?: string;
	notes?: string;
	createdAt?: string;
	updatedAt?: string;
}

export type GetReferralCodesResponse = IReferralCode[];

/**
 * Admin list — all referral codes, newest first.
 */
export function getReferralCodes(): Promise<GetReferralCodesResponse> {
	return ajaxGet<GetReferralCodesResponse>({
		url: getApiUrl(Service, ReferralAPI.GetReferralCodes),
		query: {filter: '{"order":"createdAt DESC"}'},
	});
}

export interface AddReferralCodeRequestParams {
	referrerName: string;
	isActive?: boolean;
	notes?: string;
	validFrom?: string;
	validTo?: string;
}

/** Create a referral code. The server auto-generates a unique code. */
export function addReferralCode(
	data: AddReferralCodeRequestParams,
): Promise<IReferralCode> {
	return ajaxPost<AddReferralCodeRequestParams, IReferralCode>({
		data,
		url: getApiUrl(Service, ReferralAPI.AddReferralCode),
	});
}

export interface UpdateReferralCodeRequestParams {
	id: string;
	referrerName?: string;
	isActive?: boolean;
	notes?: string;
	validFrom?: string;
	validTo?: string;
}

/** Partial update via PATCH /referral-codes/{id}. */
export function updateReferralCode({
	id,
	...data
}: UpdateReferralCodeRequestParams): Promise<IReferralCode> {
	return ajaxPatch<Omit<UpdateReferralCodeRequestParams, 'id'>, IReferralCode>({
		data,
		url: `${getApiUrl(Service, ReferralAPI.UpdateReferralCode)}/${id}`,
	});
}

export function deleteReferralCode({id}: {id: string}): Promise<void> {
	return ajaxDelete<void>({
		url: `${getApiUrl(Service, ReferralAPI.DeleteReferralCode)}/${id}`,
	});
}
